version: '2'
services:
  consul:
    image: gliderlabs/consul-server
    ports:
      - 8500
    command: "-bootstrap -bind 0.0.0.0 -client 0.0.0.0 -ui"
    dns_search: ""
    labels:
      - "SERVICE_8500_CHECK_TCP=true"
      - "SERVICE_8500_CHECK_INTERVAL=15s"
      - "SERVICE_8500_NAME=consul"
      - "SERVICE_8500_TAGS=urlprefix-consul.tugboat.zone/"
    restart: always

  registrator:
    image: gliderlabs/registrator:latest
    command: -ip 192.168.99.100 consul://consul:8500
    dns_search: ""
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    restart: always
    depends_on:
      - consul

  fabio:
    image: magiconair/fabio
    dns_search: ""
    volumes:
      - "./ssl:/ssl"
    labels:
      - "FABIO_PROXY_CS=cs=ssl;type=file;cert=/ssl/tugboat.zone-self.crt;key=/ssl/tugboat.zone-self.key"
      - "FABIO_PROXY_ADDR=:80,:443;cs=ssl"
      - "FABIO_UI_TITLE=Tugboat Services"
      - "FABIO_UI_COLOR=blue"
      - "REGISTRY_CONSUL_ADDR=consul:8500"
      - "REGISTRY_CONSUL_REGISTER_TAGS=urlprefix-fabio.tugboat.zone/,urlprefix-/"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - consul
